// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmzjcooxpubxitkbdllg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhtempjb294cHVieGl0a2JkbGxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MTIxMTcsImV4cCI6MjA1NDA4ODExN30.bq1a3HNQ580D7Yc1IDIkTlmPvwkCOOeO9k_PdN-fVGI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);